export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Chat } from './Chat'
export { default as KnowledgeManagement } from './KnowledgeManagement'
export { default as Dashboard } from './Dashboard'
